/**
 * Displays real-time swing metrics and phase-aware, source-backed coaching feedback.
 * Feedback is generated by the fundamentals engine (no magic-number if blocks).
 */

import { useMemo } from 'react'
import { calculateSwingMetrics } from '../lib/angles'
import { buildFeedback, scoreBadge } from '../lib/fundamentalsEngine'
import type { PoseLandmarks, SwingAnalysis } from '../types/pose'
import type { Sport, Handedness } from '../types/fundamentals'

interface MetricsPanelProps {
  landmarks: PoseLandmarks | null
  swingAnalysis: SwingAnalysis | null
  sport: Sport
  handedness: Handedness
}

function formatAngle(value: number): string {
  return `${value.toFixed(1)}°`
}

function formatRatio(value: number): string {
  return value.toFixed(2)
}

function formatSpeed(mph: number | null | undefined): string {
  if (mph == null || mph <= 0) return '--'
  return `${mph.toFixed(0)} mph`
}

interface MetricRowProps {
  label: string
  value: string
  hint?: string
}

function MetricRow({ label, value, hint }: MetricRowProps) {
  return (
    <div className="metric-row">
      <span className="metric-label">{label}</span>
      <span className="metric-value">{value}</span>
      {hint && <span className="metric-hint">{hint}</span>}
    </div>
  )
}

export function MetricsPanel({
  landmarks,
  swingAnalysis,
  sport,
  handedness,
}: MetricsPanelProps) {
  const metrics = useMemo(() => {
    if (!landmarks || landmarks.length < 33) return null
    return calculateSwingMetrics(landmarks, handedness)
  }, [landmarks, handedness])

  const scoredMetrics = useMemo(() => {
    if (!metrics) return []
    return buildFeedback(metrics, swingAnalysis?.phase ?? 'idle', sport, handedness)
  }, [metrics, swingAnalysis?.phase, sport, handedness])

  if (!landmarks) {
    return (
      <aside className="metrics-panel">
        <h3>Swing Metrics</h3>
        <p className="placeholder">
          Upload a video or start camera to see real-time swing analysis.
        </p>
      </aside>
    )
  }

  if (!metrics) {
    return (
      <aside className="metrics-panel">
        <h3>Swing Metrics</h3>
        <p className="placeholder">Waiting for pose detection...</p>
      </aside>
    )
  }

  const leadLabel = handedness === 'right' ? 'Lead (L)' : 'Lead (R)'
  const rearLabel = handedness === 'right' ? 'Rear (R)' : 'Rear (L)'

  return (
    <aside className="metrics-panel">
      <h3>Swing Metrics</h3>

      <div className="metrics-grid">
        <div className="metrics-section">
          <h4>Body Rotation</h4>
          <MetricRow
            label="Hip-Shoulder Sep."
            value={formatAngle(metrics.hipShoulderSeparation)}
            hint="X-factor"
          />
          <MetricRow
            label="Bat/Club Angle"
            value={formatAngle(metrics.batAngle)}
            hint="Forearm axis"
          />
        </div>

        <div className="metrics-section">
          <h4>Arms</h4>
          <MetricRow
            label={`${leadLabel} Elbow`}
            value={formatAngle(metrics.leadElbowAngle)}
          />
          <MetricRow
            label={`${rearLabel} Elbow`}
            value={formatAngle(metrics.rearElbowAngle)}
          />
          <MetricRow
            label="Hand Height"
            value={formatRatio(metrics.handHeight)}
          />
        </div>

        <div className="metrics-section">
          <h4>Lower Body</h4>
          <MetricRow
            label={`${leadLabel} Knee`}
            value={formatAngle(metrics.leadKneeAngle)}
          />
          <MetricRow
            label={`${rearLabel} Knee`}
            value={formatAngle(metrics.rearKneeAngle)}
          />
          <MetricRow
            label="Stance Width"
            value={formatRatio(metrics.stanceWidth)}
            hint="× hip width"
          />
        </div>

        <div className="metrics-section">
          <h4>Swing Dynamics</h4>
          <MetricRow
            label="Swing Speed"
            value={formatSpeed(swingAnalysis?.currentSwingSpeed)}
            hint="live"
          />
          <MetricRow
            label="Peak Speed"
            value={formatSpeed(swingAnalysis?.peakSwingSpeed)}
            hint="max"
          />
          <MetricRow
            label="Contact"
            value={swingAnalysis?.contactDetected ? 'DETECTED' : 'Watching...'}
            hint={swingAnalysis?.phase ?? ''}
          />
          {swingAnalysis?.contactDetected && (
            <>
              <MetricRow
                label="Launch Angle"
                value={swingAnalysis.launchAngle != null
                  ? formatAngle(swingAnalysis.launchAngle)
                  : '--'}
                hint="estimated"
              />
              <MetricRow
                label="Exit Velocity"
                value={formatSpeed(swingAnalysis.exitVelocity)}
                hint="estimated"
              />
            </>
          )}
        </div>
      </div>

      <div className="metrics-feedback">
        <h4>Analysis</h4>
        {scoredMetrics.length > 0 ? (
          <ul>
            {scoredMetrics.map((sm, i) => (
              <li
                key={i}
                className={
                  sm.score === 'ideal'
                    ? 'feedback-ideal'
                    : sm.score === 'too_low' || sm.score === 'too_high'
                    ? 'feedback-warn'
                    : ''
                }
              >
                {scoreBadge(sm.score)} {sm.feedback}
              </li>
            ))}
          </ul>
        ) : (
          <p className="placeholder">Analyzing swing mechanics...</p>
        )}
      </div>
    </aside>
  )
}
